import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { MusicMlGeneratedModule, MusicMlGeneratedSharedModule } from './generated/module';
import { MusicMlValidator, registerValidationChecks } from './music-ml-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MusicMlAddedServices = {
    validation: {
        MusicMlValidator: MusicMlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MusicMlServices = LangiumServices & MusicMlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MusicMlModule: Module<MusicMlServices, PartialLangiumServices & MusicMlAddedServices> = {
    validation: {
        MusicMlValidator: () => new MusicMlValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMusicMlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MusicMl: MusicMlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MusicMlGeneratedSharedModule
    );
    const MusicMl = inject(
        createDefaultModule({ shared }),
        MusicMlGeneratedModule,
        MusicMlModule
    );
    shared.ServiceRegistry.register(MusicMl);
    registerValidationChecks(MusicMl);
    return { shared, MusicMl };
}
